# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa2ffe346803ad91c432e7d8a39b757acd210effba858a46703fca54340ff853d9cfa763612594fb1b31a7a74ff1b52706ea34c71a59bb31872e8f54b6ed5054

test:
  secret_key_base: 93425c9413c5aa1e3976eb50d73d2d9bc7120a82194c134c69bfea30502dba181058162c578861c3faefd60d524d5079ee88714e245b2c9ee896328ee01ff5b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
